import { L } from '../game/i18n';

/** Interface copy (story text lives with the game data). */
export const UI = {
  title: L('THE LAST ROOM', 'THE LAST ROOM'),
  tagline: L('A ROOM WITH NO WAY OUT.', '출구 없는 방.'),
  startGame: L('START GAME', '새로 시작'),
  continueGame: L('CONTINUE', '이어하기'),
  howToPlay: L('HOW TO PLAY', '플레이 방법'),
  sound: L('SOUND', '사운드'),
  on: L('ON', '켜짐'),
  off: L('OFF', '꺼짐'),
  language: L('LANGUAGE', '언어'),
  achievements: L('ACHIEVEMENTS', '업적'),
  back: L('Back', '돌아가기'),
  close: L('Close', '닫기'),
  confirm: L('Confirm', '확인'),
  cancel: L('Cancel', '취소'),
  startOverTitle: L('Start over?', '처음부터 시작할까요?'),
  startOverBody: L('Your current progress will be erased.', '현재 진행 상황이 모두 지워집니다.'),
  credits: L(
    'All visuals and sounds are generated in your browser.',
    '모든 그래픽과 사운드는 브라우저에서 실시간으로 생성됩니다.',
  ),
  lockedAchievement: L('???', '???'),

  howTitle: L('How to play', '플레이 방법'),
  howLines: [
    L('Look around. Things worth examining catch the light when you hover or glint now and then.', '방을 둘러보세요. 조사할 만한 물건은 마우스를 올리면 빛나거나, 가끔 반짝입니다.'),
    L('Tap an object to examine it up close. Some things can be picked up.', '물건을 누르면 가까이서 조사합니다. 어떤 물건은 가져갈 수 있습니다.'),
    L('Tap an item in your inventory to hold it, then tap something in the room to use it.', '인벤토리의 아이템을 눌러 손에 든 뒤, 방 안의 물건을 누르면 사용합니다.'),
    L('While holding an item, tap another item to combine them.', '아이템을 든 채로 다른 아이템을 누르면 조합합니다.'),
    L('Everything you learn is written in your notebook. Stuck? Hints come in three steps.', '알아낸 단서는 모두 수첩에 기록됩니다. 막히면 3단계 힌트를 쓰세요.'),
    L('Progress saves automatically. On a narrow screen, drag to look around.', '진행 상황은 자동 저장됩니다. 화면이 좁으면 드래그해서 둘러보세요.'),
  ],
  howKeys: L('Keyboard: Tab to move · Enter to select · Esc to go back · ←/→ to look around', '키보드: Tab 이동 · Enter 선택 · Esc 뒤로 · ←/→ 둘러보기'),

  hint: L('Hint', '힌트'),
  hintsUsed: L('hints used', '힌트 사용'),
  revealHint: L('Reveal hint', '힌트 보기'),
  revealNextHint: L('Reveal next hint', '다음 힌트 보기'),
  noMoreHints: L('That is every hint for this step.', '이 단계의 힌트를 모두 보았습니다.'),
  allDone: L('Nothing left to find. Go.', '더 찾을 것은 없다. 나가자.'),
  hintCostNote: L('Hints are counted on the results screen.', '힌트 사용 횟수는 결과 화면에 표시됩니다.'),
  objective: L('Current goal', '현재 목표'),

  notebook: L('Notebook', '수첩'),
  notebookEmpty: L('Nothing noted yet. Look around.', '아직 적은 것이 없다. 방을 둘러보자.'),
  settings: L('Settings', '설정'),
  volume: L('Volume', '볼륨'),
  reduceMotion: L('Reduce motion', '움직임 줄이기'),
  backToTitle: L('Save & return to title', '저장 후 타이틀로'),
  newGame: L('NEW GAME', '새 게임'),
  eraseAll: L('Erase all data (incl. achievements)', '모든 데이터 삭제 (업적 포함)'),
  eraseTitle: L('Erase everything?', '모든 데이터를 삭제할까요?'),
  eraseBody: L('Progress, settings and achievements will be deleted.', '진행 상황, 설정, 업적이 모두 삭제됩니다.'),
  storageWarning: L('Saving is unavailable in this browser. Progress lasts until you close the tab.', '이 브라우저에서는 저장할 수 없습니다. 탭을 닫으면 진행 상황이 사라집니다.'),

  inventory: L('Inventory', '인벤토리'),
  inventoryEmpty: L('Empty', '비어 있음'),
  inspect: L('Inspect', '살펴보기'),
  putAway: L('Put away', '내려놓기'),
  holding: L('Holding', '들고 있음'),
  holdingHelp: L('Tap an object — or another item — to use it.', '물건이나 다른 아이템을 눌러 사용하세요.'),
  useItem: L('Use', '사용'),
  take: L('Take', '가져가기'),
  prevPage: L('Previous page', '이전 페이지'),
  nextPage: L('Next page', '다음 페이지'),
  turnOver: L('Turn over', '뒤집기'),
  holdToLamp: L('Hold it near the lamp', '램프 가까이 대기'),
  page: L('Page', '페이지'),

  lookLeft: L('Look left', '왼쪽 보기'),
  lookRight: L('Look right', '오른쪽 보기'),
  dragHint: L('Drag to look around', '드래그해서 둘러보기'),

  setHands: L('Set the hands', '바늘 고정'),
  hour: L('Hour', '시'),
  minute: L('Minute', '분'),
  clockStopped: L('The pendulum hangs still.', '추가 멈춰 있다.'),
  towerZoom: L('Look closer', '자세히 보기'),
  enter: L('Enter', '입력'),
  clear: L('Clear', '지우기'),
  turnHandle: L('Turn the handle', '손잡이 돌리기'),
  keyhole: L('Keyhole', '열쇠 구멍'),
  drawerLocked: L('Locked. A small brass-rimmed keyhole.', '잠겨 있다. 황동 테두리의 작은 열쇠 구멍.'),
  doorLocked: L(
    'Three locks: an iron keyhole, a brass time dial, and a bolt that will not move.',
    '세 개의 잠금장치: 무쇠 열쇠 구멍, 황동 시간 다이얼, 꿈쩍도 않는 빗장.',
  ),
  doorKeyNeeded: L('The keyhole is large, shaped like a clock face.', '시계 모양의 커다란 열쇠 구멍.'),
  dialHelp: L('Set a time, then turn the handle.', '시간을 맞춘 뒤 손잡이를 돌리세요.'),
  safeMaker: L('VARN & SONS · 1911', 'VARN & SONS · 1911'),
  empty: L('Empty.', '비어 있다.'),

  skip: L('Skip', '건너뛰기'),
  time: L('TIME', '플레이 시간'),
  hintsLabel: L('HINTS USED', '힌트 사용'),
  puzzlesLabel: L('PUZZLES SOLVED', '해결한 퍼즐'),
  playAgain: L('PLAY AGAIN', '다시 하기'),
  newAchievement: L('Achievement unlocked', '업적 달성'),
  secretEnding: L('SECRET ENDING', '숨겨진 결말'),
  ending: L('ENDING', '엔딩'),
  sceneOpen: L('Examining', '조사 중'),
} as const;
